language: java
jdk:
  - openjdk10
dist: trusty
sudo: false

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - chmod +x mvnw
install:
  - ./mvnw clean install
script:
  - bash <(curl -s https://codecov.io/bash)